kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: ink-cluster

nodes:
  - role: control-plane
    labels:
      ingress-ready: "true"
    # To enable NodePort mapping on the host machine. This redirection
    # allows accessing NodePort services via localhost:NodePort on the host.
    # This is not needed in production environments and is a PODMAN redirection
    # to the control plane node.
    extraPortMappings:
      - containerPort: 30080       # Java Service NodePort
        hostPort: 30080
        protocol: TCP
      - containerPort: 30081       # Go Service NodePort
        hostPort: 30081
        protocol: TCP
      - containerPort: 80          # Ingress Port HTTP
        hostPort: 80
        protocol: TCP
      - containerPort: 443         # HTTPS (not used yet)
        hostPort: 443
        protocol: TCP

  - role: worker
    labels:
      ingress-ready: "true"

  - role: worker
    labels:
      ingress-ready: "true"
